# Generated by Django 5.2.4 on 2025-07-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='application_key',
            field=models.CharField(blank=True, help_text='SHA512 hash for unlocking extra features', max_length=128, null=True),
        ),
    ]
